version: '3' # 設定ファイルの文法のバージョン３を利用する。

services:

  # 1. phpモジュールを搭載したapacheをインストールするコンテナ。
  php:
    build: ./php # phpディレクトリのDockerfileに基づいてコンテナ作成
    volumes:
      - ../www:/var/www # ホストのhtmlディレクトリをphpコンテナのドキュメントルートと同期。
    ports:
      - 8080:80 # ホストの8080番ポートをコンテナの80番ポートにフォワード（転送）
    depends_on:
      - mysql

  # 2. mysqlをインストールするコンテナ
  mysql:
    image: mysql:5.7 # mysql5.7のイメージをそのまま利用。
    # mysqlの起動時に文字コードを指定
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0
    volumes:
      - ./db:/var/lib/mysql # ホストOSのdbフォルダ内にmysqlコンテナのDBの内容を保存
    environment:
      - MYSQL_ROOT_PASSWORD=root # mysqlのルートパスワードを設定
      - MYSQL_DATABASE=sample # デフォルトで作成するデータベース名を設定
      - MYSQL_USER=testuser # デフォルトで作成するDBユーザー名を設定
      - MYSQL_PASSWORD=password # デフォルトで作成するDBユーザーのパスワードを設定
      - "TZ=Asia/Tokyo" # タイムゾーンを設定

  # 3. phpmyadminをインストールするコンテナ
  phpmyadmin:
    image: phpmyadmin/phpmyadmin # phpmyadminのコンテナイメージをそのまま利用
    environment:
      - PMA_HOST=mysql # 上記で作成したmysqlコンテナに接続
    depends_on:
      - mysql # 上記で作成したmysqlコンテナとリンクする
    ports:
      - 8888:80 # ホストの8888番ポートをphpmyadminコンテナの80番ポートに転送
    volumes:
      - ./pma/sessions:/sessions # ホストOSのpmaディレクトリ内にphpmyadminコンテナのセッションファイルを保存